In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import platform
import seaborn as sns

import os
# OS별 폰트 설정
if os.name == "posix":  # macOS or Linux
    if platform.system() == "Darwin":  # macOS
        mpl.rc('font', family='AppleGothic')
    else:  # Linux
        # 보통 Ubuntu에 Noto Sans CJK 설치 권장
        mpl.rc('font', family='NanumGothic')  
elif os.name == "nt":  # Windows
    mpl.rc('font', family='Malgun Gothic')
    
# 마이너스 깨짐 방지
mpl.rcParams['axes.unicode_minus'] = False

---
```
spotify API 에서 가져올 수 있는 데이터
release_date
popularity
```
---

In [15]:
test = pd.read_csv("../data/spotify/20250925/KrWeekly.csv")

In [20]:
test.head(20)

,rank,uri,artist_names,track_name,source,peak_rank,previous_rank,weeks_on_chart,streams
0,1,spotify:track:7tI8dRuH2Yc6RuoTjxo4dU,Jimin,Who,BIGHIT MUSIC,1,1,62,1020755
1,2,spotify:track:3LWVXp636uLT356Rj08Jaz,Jimin,Be Mine,BIGHIT MUSIC,2,5,62,539309
2,3,spotify:track:59hVbgr8rfYkDbHfr8RcGI,Kenshi Yonezu,IRIS OUT,Sony Music Labels Inc.,3,23,2,491722
3,4,spotify:track:27xkOIER6uDLKALIelHylZ,Jin,Don’t Say You Love Me,BIGHIT MUSIC,2,2,19,443703
4,5,spotify:track:1CPZ5BxNNd0n0nF4Orb9JS,"HUNTR/X, EJAE, AUDREY NUNA, REI AMI, KPop Demo...",Golden,K-Pop Demon Hunters,1,3,14,364288
5,6,spotify:track:2HRgqmZQC0MC7GeNuDIXHN,"Jung Kook, Latto",Seven (feat. Latto) (Explicit Ver.),BIGHIT MUSIC,1,7,115,297798
6,7,spotify:track:7JQH2lBMZ10ztDnpoeq6Ki,데이먼스 이어 Damons year,yours,WM Korea,7,9,156,293356
7,8,spotify:track:6OWWZtNQORY1McaZmOrwhc,CORTIS,GO!,Republic Records – CORTIS,8,8,3,292718
8,9,spotify:track:1sUjTLLCJzcxC15GUBrOlg,aespa,Rich Man,SM Entertainment,4,4,3,275391
9,10,spotify:track:5H1sKFMzDeMtXwND3V6hRY,BLACKPINK,JUMP,YG Entertainment,3,6,11,266437
10,11,spotify:track:3Ua0m0YmEjrMi9XErKcNiR,Jimin,Like Crazy,BIGHIT MUSIC,1,15,131,226123
11,12,spotify:track:02sy7FAs8dkDNYsHp4Ul3f,"Saja Boys, Andrew Choi, Neckwav, Danny Chung, ...",Soda Pop,K-Pop Demon Hunters,4,10,14,225435
12,13,spotify:track:40UVUuyy5RfpO0awclCttA,ALLDAY PROJECT,FAMOUS,THEBLACKLABEL,3,11,13,216589
13,14,spotify:track:02BcXEH1zJYbXSabPtNlKf,"Don Toliver, Doja Cat, F1 The Album",Lose My Mind (feat. Doja Cat) [From F1® The Mo...,Atlantic Records,6,12,13,206857
14,15,spotify:track:4ecdsGz3Hg6TKPwQ0ZOdJz,CORTIS,FaSHioN,Republic Records – CORTIS,15,16,3,201030
15,16,spotify:track:6qafqn8bBMy7t5c5WqpyRk,Jimin,Closer Than This,BIGHIT MUSIC,2,22,92,198276
16,17,spotify:track:7gMfVc4zfNIxuMyMGglOHa,Jimin,Rebirth (Intro),BIGHIT MUSIC,4,24,62,192174
17,18,spotify:track:4p0uVFAXKUISu8yp9gNtWE,ILLIT,Billyeoon Goyangi (Do the Dance),BELIFT LAB,6,14,15,190191
18,19,spotify:track:1agDCV4zQqaFwJQNsTgmL1,"Jimin, Loco",Smeraldo Garden Marching Band (feat. Loco),BIGHIT MUSIC,2,19,65,188541
19,20,spotify:track:5EoV2HmAlkqN1XvsIjOBZZ,Hearts2Hearts,STYLE,SM Entertainment,10,20,14,184961

In [17]:
test.describe()

             rank   peak_rank  previous_rank  weeks_on_chart       streams
count  200.000000  200.000000     200.000000      200.000000  2.000000e+02
mean   100.500000   43.415000      90.550000       49.315000  1.143711e+05
std     57.879185   44.492705      59.369616       50.322535  9.419222e+04
min      1.000000    1.000000      -1.000000        1.000000  6.423000e+04
25%     50.750000    6.000000      38.750000       13.000000  7.264050e+04
50%    100.500000   25.500000      89.500000       31.000000  8.566550e+04
75%    150.250000   70.000000     141.250000       69.000000  1.215912e+05
max    200.000000  191.000000     199.000000      227.000000  1.020755e+06

In [18]:
test[test['weeks_on_chart'] == (test['weeks_on_chart'].max())]

,rank,uri,artist_names,track_name,source,peak_rank,previous_rank,weeks_on_chart,streams
142,143,spotify:track:5BqwC9kOBbqYkzdOKeXFFk,JANNABI,for lovers who hesitate,PEPONI MUSIC,55,144,227,74247

In [24]:
# 1. source별 등장 횟수 계산
counts = test['source'].value_counts()

# 2. 등장 횟수가 1인 source 값만 추출
unique_sources = counts[counts == 1].index

# 3. 원본 df에서 필터링
filtered = test[test['source'].isin(unique_sources)]
filtered

,rank,uri,artist_names,track_name,source,peak_rank,previous_rank,weeks_on_chart,streams
29,30,spotify:track:4xeugB5MqWh0jwvXZPxahq,WOODZ,Drowning,EDAM Entertainment,9,39,51,151260
31,32,spotify:track:77U0fCBBkM4MfTBUZBzaF9,"Mark Vank, Samu",4AM IN IBIZA,ICY,32,-1,1,142216
32,33,spotify:track:4LJJxB4a47mreJAfKwbGEM,DAYOUNG,body,STARSHIP Entertainment,33,164,2,141149
41,42,spotify:track:7wLJ4xzxNss5abZ1kXs242,"Car, the garden",Closely Far Away,니즈뮤직,38,50,54,129737
46,47,spotify:track:15HNdxGKNCIO9pgaY4n7FU,OFFICIAL HIGE DANDISM,Pretender,PONY CANYON INC.,47,56,67,124163
48,49,spotify:track:27x2IrIGwr56QWkqJ4cu9I,IU,"Bye, Summer",EDAM ENTERTAINMENT,30,30,3,123011
53,54,spotify:track:5BZsQlgw21vDOAjoqkNgKb,Justin Bieber,DAISIES,"JRC Entertainment, LLC / ILH Production Co. LL...",17,41,11,113250
54,55,spotify:track:2Gs0iF27my40p0dANv2rAg,"MXZI, Dj Samir, DJ Javi26",MONTAGEM XONADA,Lunar Media,55,73,5,111110
56,57,spotify:track:7kjVCymE7vn0HizmGCGFWQ,Lim Young Woong,Heavenly Ever After,Mulgogi Music / ADA,9,52,24,108858
62,63,spotify:track:7so0lgd0zP2Sbgs2d7a1SZ,"Lady Gaga, Bruno Mars",Die With A Smile,Interscope Records,6,63,58,106685
69,70,spotify:track:373fb3tsAbcShtD2RZ8edv,Brown Eyes,벌써 일년,CJ E&M MUSIC,70,75,28,101308
79,80,spotify:track:7CkjU55ROZSwb95dzGan0o,Geeks,Officially Missing You,"킹핀엔터테인먼트, GRDL",77,91,55,96775
81,82,spotify:track:3be9ACTxtcL6Zm4vJRUiPG,yung kai,blue,BMG Rights Management (US) LLC,26,94,40,93747
84,85,spotify:track:1osW08ygBwopWmjWzqWbfJ,Yerin Baek,Antifreeze,Blue Vinyl,11,100,49,90005
86,87,spotify:track:0VdwOoAKPe9aGahkpllfkH,BUMJIN,A Letter,JMG(더블엑스엔터테인먼트),61,88,87,89669
90,91,spotify:track:2NtidJuimmXzUsExfMYcvk,BOYNEXTDOOR,"IF I SAY, I LOVE YOU",KOZ Entertainment,6,87,38,88535
92,93,spotify:track:4OHq2ao4pXmGq9OOuP3lxb,"Primary, Dynamicduo",Johnny,2018 Amoeba Culture,93,134,18,87319
97,98,spotify:track:6oNLSQX8bcAdbCElZYju3v,fromis_9,Supersonic,PLEDIS Entertainment,12,97,59,86204
99,100,spotify:track:0fK7ie6XwGxQTIkpFoWkd1,JENNIE,like JENNIE,Sony Music Entertainment,2,99,29,85988
101,102,spotify:track:3HIDWyZGwSe5MhrSP890nc,Lim Jae Hyun,Rhapsody of Sadness,"DAWN TAPE, IK PRODUCTION",65,103,63,84710
103,104,spotify:track:1YXot2MLAG9sttepCtBRM7,Vaundy,踊り子,SDR Inc.,18,127,90,83261
107,108,spotify:track:2CGNAOSuO1MEFCbBRgUzjd,"Kendrick Lamar, SZA",luther (with sza),"pgLang, under exclusive license to Interscope ...",3,107,44,82263
114,115,spotify:track:33xRp6ZX1DKraRFHR9ZDck,Choi Yu Ree,Forest,쇼파르엔터테인먼트,93,93,30,80873
127,128,spotify:track:7tGDXCPLpAScEwmqab9YZd,Novelbright,Walking with you,Emperor Mode,128,163,3,77257
131,132,spotify:track:4pimesHwLgyqCpvKtdYpcV,GongGongGoo009,Walk,GongGongGoo009,126,133,7,76665
140,141,spotify:track:075HUD50Nuea3rNaABIsNZ,tuki.,晩餐歌 - Bansanka,月面着陸計画,79,155,68,74468
142,143,spotify:track:5BqwC9kOBbqYkzdOKeXFFk,JANNABI,for lovers who hesitate,PEPONI MUSIC,55,144,227,74247
145,146,spotify:track:1BxfuPKGuaTgP7aM0Bbdwr,Taylor Swift,Cruel Summer,Taylor Swift,24,142,120,73352
148,149,spotify:track:30tYWTkLIQtZWnRIOqcHnJ,"Car, the garden",나무,Kakao Entertainment,114,158,31,72770
150,151,spotify:track:11gZL0HigsqfzjTHOpdFjE,"Nakama, Mc Staff",MENTE MÁ,void,151,162,4,72471
156,157,spotify:track:7t4Z19BqZ23ExgdiOP0nf6,fromis_9,LIKE YOU BETTER,"ASND ENTERTAINMENT CO., LTD",18,156,13,70939
159,160,spotify:track:20QI1DhCFz7pN8rATkNguv,10CM,To Reach You,CAM,11,152,25,70302
160,161,spotify:track:3s761CQaziQ0GEN1yUkIsG,Nerd Connection,‎Good Night Good Dream,Your Summer,81,166,155,70233
161,162,spotify:track:2LBqCSwhJGcFQeTHMVGwy3,The Weeknd,Die For You,Universal Republic Records,36,176,159,70171
162,163,spotify:track:6xV7Be6XEvkSnighmh2Tzj,"Tyler, The Creator",Sugar On My Tongue,Columbia,115,115,3,70081
164,165,spotify:track:34HSEUn4YGAFBW9OHGIkU7,george,Boat,CRAFT AND JUN,56,-1,36,70058
168,169,spotify:track:3scRk3rUGIwpCg9kMNrtEQ,Baek A,Amor,Baek A,17,170,135,69746
170,171,spotify:track:7csMuPqdOPaFKby0AoRYL5,BUZZ,가시,에이원피플,134,185,26,69321
171,172,spotify:track:3kXoKlD84c6OmIcOLfrfEs,"Earth, Wind & Fire",September,Columbia/Legacy,158,-1,2,69317
173,174,spotify:track:4p4yxplNCSmt9xfaAMpcd5,BIG Naughty,Vancouver,H1GHR MUSIC RECORDS,40,199,148,69228
177,178,spotify:track:7qiZfU4dY1lWllzX7mPBI3,Ed Sheeran,Shape of You,Atlantic Records UK,110,184,89,68600
179,180,spotify:track:0QzuaeCEEOV40Pn7IvKEny,Dhruv,double take,Little Worry/RCA Records,42,188,220,68417
181,182,spotify:track:21IVUjbu1ms4ZISGt74NCy,"HAON, GISELLE",Skrr (feat. GISELLE),KC,24,195,29,67812
185,186,spotify:track:3GG5KPuvG7qokLoKReboHI,Martin Smith,Paint On Spring - Remastering,브이엔터테인먼트,38,182,25,66962
186,187,spotify:track:50kpGaPAhYJ3sGmk6vplg0,Justin Bieber,Love Yourself,RBMG/Def Jam,79,189,219,66899
189,190,spotify:track:4PBtSN6dNFXA9RUkx5e3W9,Woody,Sadder Than Yesterday,GOLDEN MOON(GDM),129,-1,14,65895
191,192,spotify:track:0N8Xztr4pBHJ7V0moJWhbO,Aimyon,愛を伝えたいだとか,WM Japan,14,-1,42,65546
195,196,spotify:track:0VjIjW4GlUZAMYd2vXMi3b,The Weeknd,Blinding Lights,Republic Records,8,190,141,64469
199,200,spotify:track:2i3HoDE1ZvQ2bh2ZmgpSug,Nerd Connection,Silently Completely Eternally,유어썸머,85,-1,27,64230

In [26]:
# 신규 진입 차트
# previous_rank 가 -1 (전주에 차트에 없었음)  +( peak_rank = rank ) 최고 랭크가 현재의 랭크임
test[(test['previous_rank'] == -1) & (test['rank'] == test['peak_rank'])]

,rank,uri,artist_names,track_name,source,peak_rank,previous_rank,weeks_on_chart,streams
31,32,spotify:track:77U0fCBBkM4MfTBUZBzaF9,"Mark Vank, Samu",4AM IN IBIZA,ICY,32,-1,1,142216
93,94,spotify:track:7zUD9iJoEOBRUE3UtHhdwR,PLAVE,숨바꼭질 (Hide and Seek),VLAST,94,-1,1,87187
135,136,spotify:track:4oE7MyJhqSD3BaHRpNs8Nl,"Kenshi Yonezu, Hikaru Utada",JANE DOE,Sony Music Labels Inc.,136,-1,1,75268
149,150,spotify:track:7MGUDGEQpcqf29gWAmJyy4,d4vd,Sleep Well,Darkroom/Interscope Records,150,-1,1,72697
190,191,spotify:track:5tEouf2s1SPwAIkOHnvWtQ,Beenzino,Aqua Man,Stone Music Entertainment,191,-1,5,65762

In [27]:
# 역주행 차트 
test[(test['previous_rank'] == -1) & (test['rank'] != test['peak_rank'])]

,rank,uri,artist_names,track_name,source,peak_rank,previous_rank,weeks_on_chart,streams
76,77,spotify:track:7oYCBKvdjrqp5vDbhDBuac,Kenshi Yonezu,KICK BACK,Sony Music Labels Inc.,11,-1,66,98035
164,165,spotify:track:34HSEUn4YGAFBW9OHGIkU7,george,Boat,CRAFT AND JUN,56,-1,36,70058
171,172,spotify:track:3kXoKlD84c6OmIcOLfrfEs,"Earth, Wind & Fire",September,Columbia/Legacy,158,-1,2,69317
189,190,spotify:track:4PBtSN6dNFXA9RUkx5e3W9,Woody,Sadder Than Yesterday,GOLDEN MOON(GDM),129,-1,14,65895
191,192,spotify:track:0N8Xztr4pBHJ7V0moJWhbO,Aimyon,愛を伝えたいだとか,WM Japan,14,-1,42,65546
196,197,spotify:track:7JJmb5XwzOO8jgpou264Ml,Shawn Mendes,There's Nothing Holdin' Me Back,Island Records,108,-1,39,64457
199,200,spotify:track:2i3HoDE1ZvQ2bh2ZmgpSug,Nerd Connection,Silently Completely Eternally,유어썸머,85,-1,27,64230